name: animated_menu
description: A flutter package that will help you to create animated menu with ease.
version: 1.0.0
homepage: https://github.com/mantreshkhurana/animated_menu
repository: https://github.com/mantreshkhurana/animated_menu

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  figma_squircle: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true